<?php
echo "<!DOCTYPE html>\n"; 
echo "\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "	<meta charset=\"UTF-8\">\n"; 
echo "	<title>PHP-based web application</title>\n"; 
echo "	<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "	<div class=\"page\">\n"; 
echo "		<div class=\"header\">\n"; 
echo "			<a href=\"index.php\" id=\"logo\"><img src=\"resources/logo.jpg\" alt=\"logo\"></a>\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<p>Welcome to the About Us</p>\n"; 

echo "				</div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\"><span>Home</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li class=\"selected\">\n"; 
echo "							<a href=\"about.php\"><span>About</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"work.php\"><span>Work</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\"><span>Artists</span></a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<form action=\"index.php\">\n"; 
echo "						<input type=\"text\" onclick=\"this.value='';\" onfocus=\"this.select()\" onblur=\"this.value=!this.value?'Enter search query':this.value;\" value=\"Enter search query\">\n"; 
echo "						<input type=\"submit\" value=\"\">\n"; 
echo "					</form>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "		<div class=\"body\">\n"; 
echo "			<div class=\"about\">\n"; 
echo "				<ul>\n"; 
echo "					<li class=\"selected\">\n"; 
echo "						<a href=\"index.php\">Home Page</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work.php\">Work</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"artist.php\">Artists</a>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "				<div>\n"; 
echo "					<div>\n"; 
echo "						<span></span><img src=\"resources/art-images/paintings/medium/102020.jpg\" alt=\"\">\n"; 
echo "					</div>\n"; 
echo "					<p><strong>Student ID: 999990749. Name: Dharani Teja Kumar Chalamalasetti</strong></p>\n"; 
echo "					<p>\n"; 
echo "						The mantra for a successful art or artist website has been and continues to be \"Keep it fast, simple, easy and organized.\" Navigation and content must be straightforward in order to attract visitors in the first place and keep them on the site once they get there. First-time visitors to any artist website should know as quickly as possible where they are, who the artist is, what their art looks like, what it's about, why it's worth seeing (and hopefully worth buying), and how to move around in order to get wherever they want to go. Sites that lack these basics or make other common errors won't be able to attract and hold visitors, and will likely end up lost in the vast morass of nonfunctional and confusing art websites that overpopulate the Internet. \n"; 
echo "					</p>\n"; 
echo "					<p>\n"; 
echo "						Think of it this way-- you're like the curator of your own museum; make sure your art is organized in a way that's easy to understand and navigate. People who already know you or who are familiar with your art know how to navigate your website and get wherever they want to go. So they're all taken care of. It's the complete strangers you should be most concerned about, those who hear about you for the first time and what to take a look around, and especially those who land on your site by chance, accident or happenstance. The Internet is all about exposing your art to unfamiliar audiences, welcoming new visitors and broadening your fan base, so whenever someone lands on your website who knows little or nothing about you or your art, you want to do your absolute best to get them oriented fast and over to wherever they want to go. \n"; 
echo "					</p>\n"; 
echo "					<p>\n"; 
echo "						The title line consists of keywords that accurately and specifically describe a page's content, like a news story headline tells what you're about to read. Many artist websites completely waste title line opportunities using the exact same line on every page of the site, like \"Mike Miller art\" or \"Judy Smith artist.\" The title line, in case you don't know, usually appears at or near the top of your browser window outside the page, on index tabs or tab bars, not in the content of the page itself. It's one of the most important lines on a webpage and often the line that appears in search results, like on Google. Each title line on each individual page of your website-- even each image page-- should be unique, specific and descriptive of the contents on that page. This way, each page will have a slightly different appearance on search engines, meaning more keywords searchable on search engines, and most importantly, more opportunities for your website to appear in search results, which will hopefully translate to more visitors to your site. \n"; 
echo "					</p>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "<div class=\"footer\">\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\">Home</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\">About</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"work.php\">Work</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\">Artists</a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<p>\n"; 
echo "						PHP-based website\n"; 
echo "					</p>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>