<?php
echo "<!DOCTYPE html>\n"; 
echo "\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "	<meta charset=\"UTF-8\">\n"; 
echo "	<title>PHP-based web application</title>\n"; 
echo "	<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "	<div class=\"page\">\n"; 
echo "		<div class=\"header\">\n"; 
echo "			<a href=\"index.php\" id=\"logo\"><img src=\"resources/logo.jpg\" alt=\"logo\"></a>\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<p>Welcome to the Artists Page</p>\n"; 
echo "				</div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\"><span>Home</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\"><span>About</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"work.php\"><span>Work</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li class=\"selected\">\n"; 
echo "							<a href=\"artist.php\"><span>Artists</span></a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<form action=\"index.php\">\n"; 
echo "						<input type=\"text\" onclick=\"this.value='';\" onfocus=\"this.select()\" onblur=\"this.value=!this.value?'Enter search query':this.value;\" value=\"Enter search query\">\n"; 
echo "						<input type=\"submit\" value=\"\">\n"; 
echo "					</form>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "		<div class=\"body\">\n"; 
echo "			<div class=\"blog\">\n"; 
echo "				<ul>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/artists/medium/15.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>Edgar Degas</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								Edgar Degas, born Hilaire-Germain-Edgar De Gas, was a French artist famous for his work in painting, sculpture, printmaking and drawing. He is regarded as one of the founders of Impressionism although he rejected the term, and preferred to be called a realist. A superb draughtsman, he is especially identified with the subject of the dance, and over half of his works depict dancers. These display his mastery in the depiction of movement, as do his racecourse subjects and female nudes. \n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								 His portraits are notable for their psychological complexity and depiction of human isolation\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/artists/medium/17.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>Claude Monet</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								Claude Monet was a founder of French impressionist painting, and the most consistent and prolific practitioner of the movement's philosophy of expressing one's perceptions before nature, especially as applied to plein-air landscape painting. The term Impressionism is derived from the title of his painting Impression, Sunrise \n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								it is a renowned work described by art historian Kenneth Clark as \"a picture which those who have seen the original in Leningrad may be forgiven for claiming as the greatest picture ever painted\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/artists/medium/109.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>Sir Joshua Reynolds</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								was an influential eighteenth-century English painter, specialising in portraits and promoting the \"Grand Style\" in painting which depended on idealization of the imperfect. He was one of the founders and first president of the Royal Academy, and was knighted by George III in 1769\n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								It has been suggested that the painting may be connected with the influence of Savonarola, whose influence appears in a number of late paintings by Botticelli, though the contents of the image may have been specified by the person commissioning it.~1500~108~75~Tempera on canvas~National Gallery, London\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "				<ul class=\"paging\">\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">&#60;&#60;</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">First</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">1</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"artist.php\">2</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"artist.php\">3</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">Last</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">&#62;&#62;</a>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "<div class=\"footer\">\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\">Home</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\">About</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"work.php\">Work</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\">Artists</a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<p>\n"; 
echo "						PHP-based website\n"; 
echo "					</p>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>