<?php
echo "<!DOCTYPE html>\n"; 
echo "\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "	<meta charset=\"UTF-8\">\n"; 
echo "	<title>PHP-based web application</title>\n"; 
echo "	<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "	<div class=\"page\">\n"; 
echo "		<div class=\"header\">\n"; 
echo "			<a href=\"index.php\" id=\"logo\"><img src=\"resources/logo.jpg\" alt=\"logo\"></a>\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<p>Welcome to the Paintings</p>\n"; 
echo "				</div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\"><span>Home</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\"><span>About</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li class=\"selected\">\n"; 
echo "							<a href=\"work.php\"><span>Work</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\"><span>Artists</span></a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<form action=\"index.php\">\n"; 
echo "						<input type=\"text\" onclick=\"this.value='';\" onfocus=\"this.select()\" onblur=\"this.value=!this.value?'Enter search query':this.value;\" value=\"Enter search query\">\n"; 
echo "						<input type=\"submit\" value=\"\">\n"; 
echo "					</form>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "		<div class=\"body\">\n"; 
echo "			<div class=\"blog\">\n"; 
echo "				<ul>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/paintings/medium/15050.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>Glass of Absinthe</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								Glass of Absinthe is a painting by Edgar Degas. Some original title translations are A sketch of a French Café, then Figures at Café, the title was finally changed in 1893 to L’Absinthe (the name the piece is known by today). It is now in the permanent collection of the Musée d'Orsay in Paris. Painted in 1875-1876, it depicts two figures, a woman and man, who sit in the center and right of this painting, respectively. \n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								 The diagonal of the railing serves to demarcate the two halves of the composition, one densely packed with figures, the other all but empty, save for the two figures of the proprietor's daughter Louise-Alphonsine Fournaise and her brother, Alphonse Fournaise, Jr, which are made prominent by this contrast. \n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/paintings/medium/17020.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>Women in the Garden</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								Monet’s technique of “en plein air” painting was hard at work on this painting. Because it necessitated that he work from the same point of view as he painted, he dug a trench for the bottom half of the painting to sit in while he painted the top, due to its large size \n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								it is a renowned work described by art historian Kenneth Clark as \"a picture which those who have seen the original in Leningrad may be forgiven for claiming as the greatest picture ever painted\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/paintings/medium/45010.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>The Ghost of Vermeer van Delft</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								The Ghost of Vermeer van Delft which Can Be Used as a Table~The title refers to the Dutch painter Johannes Vermeer and the image of Vermeer viewed from his back is a reference to Vermeer's painting\n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								The Art of Painting In this image Vermeer is represented as a dark spindly figure in a kneeling position. The figure’s outstretched leg serves as a table top surface, on which sits a bottle and a small glass. This leg tapers to a baluster-like stub\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "				<ul class=\"paging\">\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">&#60;&#60;</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work.php\">First</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work.php\">1</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work2.php\">2</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work2.php\">3</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\work2.php\">Last</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">&#62;&#62;</a>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "<div class=\"footer\">\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\">Home</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\">About</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"work.php\">Work</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\">Artists</a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<p>\n"; 
echo "						PHP-based website\n"; 
echo "					</p>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>