<?php
echo "<!DOCTYPE html>\n"; 
echo "\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "	<meta charset=\"UTF-8\">\n"; 
echo "	<title>PHP-based web application</title>\n"; 
echo "	<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "	<div class=\"page\">\n"; 
echo "		<div class=\"header\">\n"; 
echo "			<a href=\"index.php\" id=\"logo\"><img src=\"resources/logo.jpg\" alt=\"logo\"></a>\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<p>Welcome to the Paintings</p>\n"; 
echo "				</div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\"><span>Home</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\"><span>About</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li class=\"selected\">\n"; 
echo "							<a href=\"work.php\"><span>Work</span></a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\"><span>Artists</span></a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<form action=\"index.php\">\n"; 
echo "						<input type=\"text\" onclick=\"this.value='';\" onfocus=\"this.select()\" onblur=\"this.value=!this.value?'Enter search query':this.value;\" value=\"Enter search query\">\n"; 
echo "						<input type=\"submit\" value=\"\">\n"; 
echo "					</form>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "		<div class=\"body\">\n"; 
echo "			<div class=\"blog\">\n"; 
echo "				<ul>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/paintings/medium/099030.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>Annunciation</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								Luncheon Boating Party~The painting depicts a group of Renoir's friends relaxing on a balcony at the Maison Fournaise along the Seine river in Chatou, France.The painter and art patron, Gustave Caillebotte, is seated in the lower right. Renoir's future wife, Aline Charigot, is in the foreground playing with a small dog. On the table is fruit and wine.\n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								 The diagonal of the railing serves to demarcate the two halves of the composition, one densely packed with figures, the other all but empty, save for the two figures of the proprietor's daughter Louise-Alphonsine Fournaise and her brother, Alphonse Fournaise, Jr, which are made prominent by this contrast. \n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/paintings/medium/05030.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>The Return of the Prodigal Son</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								The Return of the Prodigal Son is an oil painting by Rembrandt. It is among the Dutch master's final works, likely completed within two years of his death in 1669. Depicting the moment of the prodigal son's return to his father in the Biblical parable\n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								it is a renowned work described by art historian Kenneth Clark as \"a picture which those who have seen the original in Leningrad may be forgiven for claiming as the greatest picture ever painted\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<div>\n"; 
echo "							<a href=\"#\"><img src=\"resources/art-images/paintings/medium/095040.jpg\" alt=\"\"></a> <span></span>\n"; 
echo "						</div>\n"; 
echo "						<div>\n"; 
echo "							<div>\n"; 
echo "								<h3>The Mystical Nativity</h3>\n"; 
echo "							</div>\n"; 
echo "							<p>\n"; 
echo "								The Mystical Nativity is a painting of circa 1500–1501 by the Italian Renaissance master Sandro Botticelli, in the National Gallery in London. Botticelli built up the image using oil paint on canvas. It is his only signed work, and has a very unusual iconography for a Nativity. \n"; 
echo "							</p>\n"; 
echo "							<p>\n"; 
echo "								It has been suggested that the painting may be connected with the influence of Savonarola, whose influence appears in a number of late paintings by Botticelli, though the contents of the image may have been specified by the person commissioning it.~1500~108~75~Tempera on canvas~National Gallery, London\n"; 
echo "							</p>\n"; 
echo "							\n"; 
echo "						</div>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "				<ul class=\"paging\">\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">&#60;&#60;</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work.php\">First</a>\n"; 
echo "					</li>\n"; 	
echo "					<li>\n"; 
echo "						<a href=\"work.php\">1</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work2.php\">2</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"work2.php\">3</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">Last</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"#\">&#62;&#62;</a>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "<div class=\"footer\">\n"; 
echo "			<div>\n"; 
echo "				<div>\n"; 
echo "					<ul>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"index.php\">Home</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"about.php\">About</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"work.php\">Work</a>\n"; 
echo "						</li>\n"; 
echo "						<li>\n"; 
echo "							<a href=\"artist.php\">Artists</a>\n"; 
echo "						</li>\n"; 
echo "					</ul>\n"; 
echo "					<p>\n"; 
echo "						PHP-based website\n"; 
echo "					</p>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>